"""Add is_admin to SystemUser

Revision ID: fa22572cfd59
Revises: 
Create Date: 2025-12-17 09:09:37.819380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa22572cfd59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('user')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('application_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'systemuser', ['user_id'], ['user_id'])

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('credential_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'application', ['app_id'], ['app_id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('report_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'scan', ['scan_id'], ['scan_id'])

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('running', 'completed', 'failed'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'running'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('scan_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'application', ['app_id'], ['app_id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('systemuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('Admin', 'User'),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'User'"))
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('http_status',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('accessible_roles',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('url_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'scan', ['scan_id'], ['scan_id'])

    with op.batch_alter_table('violation', schema=None) as batch_op:
        batch_op.alter_column('role_attempted',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('expected_access',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('actual_access',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('violation_type',
               existing_type=mysql.ENUM('Privilege Escalation', 'Unauthorized Access', 'IDOR'),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('violation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'url', ['url_id'], ['url_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('violation_ibfk_1'), 'url', ['url_id'], ['url_id'], ondelete='CASCADE')
        batch_op.alter_column('violation_type',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('Privilege Escalation', 'Unauthorized Access', 'IDOR'),
               existing_nullable=True)
        batch_op.alter_column('actual_access',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('expected_access',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('role_attempted',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('url_ibfk_1'), 'scan', ['scan_id'], ['scan_id'], ondelete='CASCADE')
        batch_op.alter_column('accessible_roles',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
        batch_op.alter_column('http_status',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('systemuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Admin', 'User'),
               nullable=True,
               existing_server_default=sa.text("'User'"))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scan_ibfk_1'), 'application', ['app_id'], ['app_id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('running', 'completed', 'failed'),
               existing_nullable=True,
               existing_server_default=sa.text("'running'"))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('report_ibfk_1'), 'scan', ['scan_id'], ['scan_id'], ondelete='CASCADE')

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('credential_ibfk_1'), 'application', ['app_id'], ['app_id'], ondelete='CASCADE')
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('application_ibfk_1'), 'systemuser', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    # ### end Alembic commands ###
